### PR TITLE
The text will be covered by a icons

### PR DESCRIPTION
**Pull request by mik-laj**
Before and after images: http://imgur.com/a/ehQFG 
> A picture is worth a thousand words

### CODE REVIEW

**Comment by megadr01d** [comment]
Personal curiosity, which browser did you use? It works fine in Safari, OS X. The text doesn't overflow.

**Comment by mik-laj** [comment]
FF 41.0a2 (2015-07-15) Developer Edition, Linux - Kubuntu
Chrome 43.0.2357.134 (64-bit) Standard Edition, Linux - Kubuntu

**Comment by megadr01d** [comment]
For information only, just tried with Chrome 43.0.2357.134, but on Windows 7, and it's also working correctly.

**Comment by mik-laj** [comment]
I updated rainloop and the problem disappeared.

**Pull request closed without merging**
