### PR TITLE
Road to the MIT

### PR DESCRIPTION
**Pull request by RainLoop**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@RainLoop: Now I see "Legacy edition", there is a new version?

**Comment by istiak101** [comment]
I wonder what happened, good luck anyways. Hope the team is doing well. This needs to be addressed
https://blog.sonarsource.com/rainloop-emails-at-risk-due-to-code-flaw/

**Comment by istiak101** [comment]
Hmm looks fixed.
https://github.com/RainLoop/rainloop-webmail/commit/aa5d3fc89d67cb97b4b0f5c48ef32c39dd193975#diff-22b1d644ea4075b18f15da66d7f277924b8df180700f379cb6eef964a9736c07

**Comment by ner00** [comment]
Every commit points to the discontinuation of this project.

**Comment by jult** [comment]
Guess https://github.com/the-djmaze/snappymail is its continuation then? Why not just update the readme and save the world a lot of compromised webmailservers?

**Pull request merged**
