### PR TITLE
Added address parameter to vacation filter

### PR DESCRIPTION
**Pull request by panpomaly**
This patch allows to set the address parameter (https://tools.ietf.org/html/rfc5230, 4.5.  Address Parameter and Limiting Replies to Personal Messages), which is required for our usage.

An required fourth parameter is added to the vacation filter popup and automatically filled with the users email address.

Is there any chance this could be merged ?

### CODE REVIEW

**Comment by RainLoop** [comment]
Hi, 

Your functionality similar to:

**Comment by panpomaly** [comment]
I am not sure, whether this is a question or a statement.

Either way: It is similar but not the same. In our current setup, which will not change, the IAMP server does not know the email address of the user (the user ist just the user@somehost) and if we don't set the address parameter to a real email address, the vacation filter won't work. 
Adding conditionals to the not working filter, won't help. 

We used squirrelmail and the avelsieve plugin, which also sets the address parameter. 

I could explain further and/or add dovecot log messages, if wanted (but not now).

Thanks!
pp

**Comment by RainLoop** [comment]
Ok, is it required field?  Can I do it optional?

**Comment by panpomaly** [comment]
For most people it is not required (although it won't hurt, that's why i put the configured email addresses in that field). For us it would be nice if it is, but that should be configurable in the admin view.

I could just document how to use the field and it would be ok for our purpose, if it is not required.

Thanks for your effort
pp

**Comment by panpomaly** [comment]
Hi,

i wanted to ask, if there is any progress made with this feature and if we can expect a release soon ?

Thanks in advance,
pp

**Comment by RainLoop** [comment]
Hi @panpomaly,

Yes, this functionality is already available in release version.

**Comment by panpomaly** [comment]
Hey RainLoop team,

it took some time, but now i deployed a new version and it works !

Thanks again,
pp

**Pull request closed without merging**
