### PR TITLE
Virtualmin Password Change Plugin

### PR DESCRIPTION
**Pull request by icedman21**
This provides Virtualmin email users an easy way to change their email passwords from the Rainloop interface

### CODE REVIEW

**Comment by RainLoop** [comment]
```php
$sQuery = "wget -O - --quiet --http-user=$this->sAdminUser --http-passwd=$this->sAdminPassword --no-check-certificate '$sUrl?program=modify-user&domain=$sEmailDomain&pass=$sNewPassword&user=$sEmailUser'";
$sResult = shell_exec($sQuery);
```

Using `shell_exec` function is not good solution. Better use php cUrl.

**Comment by icedman21** [comment]
I already changed the code to utilize PHP cUrl.

On Mon, May 4, 2015 at 7:45 PM, RainLoop Team <notifications@github.com>
wrote:

> $sQuery = "wget -O - --quiet --http-user=$this->sAdminUser --http-passwd=$this->sAdminPassword --no-check-certificate '$sUrl?program=modify-user&domain=$sEmailDomain&pass=$sNewPassword&user=$sEmailUser'";$sResult = shell_exec($sQuery);
>
> Using shell_exec function is not good solution. Better use php cUrl.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RainLoop/rainloop-webmail/pull/628#issuecomment-98685360>
> .
>



-- 
I will be the first to step into the battlefield.  And I will be the last
to step off..

**Comment by RainLoop** [comment]
I have made some fixes in your plugin. Please test it if you want :)

**Comment by icedman21** [comment]
Thanks. That is so cool. I'm quite new with Rainloop so I don't quite know
the whole system. And I kinda made careless mistakes.

Does Rainloop have a new user creation framework? So that users can be
created for each web control panel like Virtualmin?

On Tue, May 5, 2015 at 1:17 AM, RainLoop Team <notifications@github.com>
wrote:

> I have made some fixes in your plugin. Please test it if you want :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RainLoop/rainloop-webmail/pull/628#issuecomment-98784315>
> .
>



-- 
I will be the first to step into the battlefield.  And I will be the last
to step off..

**Comment by icedman21** [comment]
I noticed that when I change the password using my plugin and go back the mail, I got an authentication failure. When i hit the browser refresh, the folder load correctly using the new credentials. I checked the logs and it seems that Rainloop is using the old credentials. How do i force a refresh or flush the old credentials upon a password change?

**Comment by RainLoop** [comment]
Interesting. It should work normally.
Thanks, I will try to fix it.

**Pull request merged**
