### PR TITLE
Use Composer to manage PHP dependencies.

### PR DESCRIPTION
**Pull request by Techwolfy**
The PHP libraries bundled with RainLoop are old and updated infrequently. Composer is to PHP what NPM is to JS, and makes it much easier to keep up-to-date. `gulp-composer` handles updates without requiring external binaries, so I was able to embed it into the main JS build process.

Additionally, it's good practice to avoid bundling multiple projects within a single git repository; unless they're heavily intertwined and all maintained by the same person/group, keeping them separate makes updates and licensing much easier.

### CODE REVIEW

**Comment by phsc84** [comment]
Also this PR, I consider highly useful. Would be great if you could merge it.

**Comment by Techwolfy** [comment]
@RainLoop Rebased on current master. Please merge this, or let me know if there's anything you'd like me to do differently.

**Comment by Techwolfy** [comment]
@RainLoop Rebased. Is this project still maintained? I don't want to keep working on Rainloop if the project has been abandoned.

**Comment by phsc84** [comment]
@RainLoop It is really sad, that you completely ignore pull requests like this. This way you frustrate developers, willing to contribute to your project. And that's the reason why an open source community dies.

**Comment by lhorace** [comment]
@Techwolfy How about we just fork it? It's open source?

**Comment by Techwolfy** [comment]
I currently maintain the Debian package for Rainloop, which includes my PRs here along with a few other changes incidental to the packaging process. That repository is hosted on https://salsa.debian.org/js-team/rainloop.

Unfortunately I don't have the time to maintain a full fork, especially if upstream isn't interested in merging changes. I don't mind making minor changes to my PRs or rebasing for a merge at @RainLoop's request, but I won't be continuing work on RainLoop beyond maintaining the package.

**Comment by lhorace** [comment]
Hello,

I plan to fork it and merge PRs and fix issues I come across there and there. Maintaining is a undertaking and I don't have any desire to implement new features. 

Is it dead or not dead is very unclear. Cheers.

**Pull request closed without merging**
