### PR TITLE
vpopmail change password plugin added

### PR DESCRIPTION
**Pull request by almas**
Kloxo-MR and vpopmail change password plugin added.

### CODE REVIEW

**Comment by RainLoop** [comment]
Thanks, but I'll make some fixes.

**Comment by almas** [comment]
Thanks :)

**Comment by RainLoop** [comment]
Ok, check the fixes please.

https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/vpopmail-change-password

**Comment by RainLoop** [comment]
One more thing, no need to use '*' in the domains. Just leave it empty.

**Pull request merged**
