### PR TITLE
Rename 'Trash' to 'Bin' for en_GB

### PR DESCRIPTION
**Pull request by felix**

### CODE REVIEW

**Comment by felix** [comment]
Well the files that I updated are just for use in the UI and have nothing to do with RFCs. The USA uses many different words and spellings to the rest of the English speaking world. See https://www.lexico.com/definition/trash and https://www.lexico.com/definition/bin for reference.

**Comment by the-djmaze** [comment]
Shouldn't it be "Rubbish" then?

**Comment by felix** [comment]
'Bin' for short, ie. "Put that email in the (rubbish) bin"

**Comment by ivnmad** [comment]
I've never seen any piece of software with GB language selected using "Bin" for the folder containing deleted files, emails, etc.
The name of that folder is normally "Deleted" [eg. see Thunderbird for emails, see Owncloud/Nextcloud for files, etc.] when GB language is selected, but "Trahs" is also common. As said, never seen "Bin" though.

My 2 cents..

**Comment by felix** [comment]
'Bin' or 'Deleted' is not a big deal. But not 'Trash'.

**Comment by felix** [comment]
> I've never seen any piece of software with GB language selected using "Bin" for the folder containing deleted files, emails, etc. The name of that folder is normally "Deleted" [eg. see Thunderbird for emails, see Owncloud/Nextcloud for files, etc.] when GB language is selected, but "Trash" is also common. As said, never seen "Bin" though.

This is gmail:

image

**Pull request closed without merging**
