### PR TITLE
Bump minimum to PHP 7.3 (as the rest is EOL)

### PR DESCRIPTION
**Pull request by the-djmaze**
The changes in this branch converted all function calls in MailSo and RainLoop libraries to be PHP 7.3+ with type hinting.
Due to the massive changes i couldn't test all conversions yet (so it might be still broken and i'm fixing it).
I've also merged the latest changes since 1.4.0 (but password_hash is different due to PHP 7.3+).

It might work in PHP 7.2 (but that is in extended support 30 Nov 2020)

Most conversion is done by using the doc comments @param and @return and the param $b*, $s*, $i* but these seem to be broken while testing.
Like: "$s*" are bool or "@param string" are "@param string|null"
That's why it takes longer and i didn't create pull requests for documentation errors.

The current marked conflicts are only CRLF vs LF (my files don't use CRLF)

### CODE REVIEW

**Comment by FlorianLaunay** [comment]
Hi @RainLoop . Do you plan to check this PR ? It will certainly resolve #1979 on PHP 7.4. Thank you @the-djmaze !

**Comment by the-djmaze** [comment]
> Hi @RainLoop . Do you plan to check this PR ? It will certainly resolve #1979 on PHP 7.4. Thank you @the-djmaze !

Actually those are already solved https://github.com/RainLoop/rainloop-webmail/commit/a250d8402544d5d3d37a0501e3e5b0854fc80bba

And this one when you use contacts https://github.com/RainLoop/rainloop-webmail/pull/1982/commits/2bb947dad4d2787e55815daff6b02585f9900ff9

**Comment by phsc84** [comment]
@the-djmaze Do you also provide a ZIP-package of your fork?
@RainLoop Would be great to merge this PR into the official repo!

**Comment by the-djmaze** [comment]
> @the-djmaze Do you also provide a ZIP-package of your fork?
> @RainLoop Would be great to merge this PR into the official repo!

Not at the moment.
Just pull the source and upload the content of rainloop/v/0.0.0/ into your existing v1.4.0 to test it.

**Comment by phsc84** [comment]
I have just tried, what you told me. Unfortunately I get the a blank page. The browser log (F12) shows the folllowing error:
www.abc.com/:1 GET https://www.abc.com/apps/mail/rainloop/v/1.14.0/static/js/min/polyfills.min.js?community net::ERR_ABORTED 404

**Comment by the-djmaze** [comment]
> I have just tried, what you told me. Unfortunately I get the a blank page. The browser log (F12) shows the folllowing error:
> [www.abc.com/:1](http://www.abc.com/:1) GET https://www.abc.com/apps/mail/rainloop/v/1.14.0/static/js/min/polyfills.min.js?community net::ERR_ABORTED 404

You are correct!
Because there is no /rainloop/v/1.14.0/static/ you should use that from the original zip.
Else install npm and run gulp on my source.
And don't use my master branch, because that has stripped functionality.

**Comment by rex2630** [comment]
Idk why, but when i tried it, it didnt worked on PHP 8. Can u make a release or something? Because for me it stucked on blank screen...

**Comment by phsc84** [comment]
Try Snappymail 2.1.1, a heavily updated fork of Rainloop. Snappymail is faster, lighter and much more futureproof (e.g. compatible with newer PHP versions).
https://github.com/the-djmaze/snappymail/releases

**Comment by rex2630** [comment]
Most of the significiant functions that i really need are missing in there, so there is no chance of even trying.

**Comment by the-djmaze** [comment]
> Idk why, but when i tried it, it didnt worked on PHP 8. Can u make a release or something? Because for me it stucked on blank screen...

Blank screen means you can find the error in the php log.
I don't create releases, that's up to the RainLoop Team (or someone else).

Since the development of RainLoop is slow, i've moved on with SnappyMail.
I wonder which significant functions you are missing...

**Comment by rex2630** [comment]
For example login via google, thats thing i cant be without

**Pull request closed without merging**
