### PR TITLE
Update include.php

### PR DESCRIPTION
**Pull request by robertol**
Remove 'webmail.' from subdomain. Very important to multiples domains.

### CODE REVIEW

**Comment by RainLoop** [comment]
Why it should be removed?
Can you please explain it in more detail?

**Comment by robertol** [comment]
Assuming that I am accessing webmail.domain.com, the system creates the folder webmail.domain.com in _data.
At first I couldn't access the webmail with url webmail.domain.com and user@domain.com denied (domain is not allowed).
With this patch, it will remove the 'webmail.' and will create just domain.com folder in _data and allowing access to this domain, same as 'www.'.

**Comment by RainLoop** [comment]
> Assuming that I am accessing webmail.domain.com,
> the system creates the folder webmail.domain.com in _data.

And this is correct.

> At first I couldn't access the webmail with url webmail.domain.com
> and user@domain.com denied (domain is not allowed).

Fixed:
https://github.com/RainLoop/rainloop-webmail/blob/master/rainloop/v/0.0.0/include.php#L203

**Comment by robertol** [comment]
Thanks.

**Pull request closed without merging**
